---
apiVersion: v1
kind: Secret
metadata:
  name: joshix-joshix-poi-backend-app-repo
  namespace: janus-argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/rosa916-rvhvd/joshix-backend-gitops
